spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: woshinidaye-dev

----
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: woshinidaye-test

----
spring:
  profiles: uat
  application:
    name: microservicecloud-config-client-test
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: woshinidaye-uat