spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev
server:
  port: 8082

----
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test
server:
  port: 8083

----
spring:
  profiles: uat
  application:
    name: microservicecloud-config-client-test
server:
  port: 8083